### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by EgorMarkor** [FDX100/Auto_Tor_IP_changer#37]
![image](https://github.com/user-attachments/assets/d597577c-7a64-45c7-9d96-57548722a75f)

**Comment by FDX100** [comment]
enter 10000 also i will lookforward to update it

**Comment by FDX100** [comment]
also you can just press enter not type 0

**Comment by Antony-M1** [comment]
@FDX100 
```
systemctl status tor
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
     Loaded: loaded (/lib/systemd/system/tor.service; enabled; vendor preset: enabled)
     Active: active (exited) since Fri 2024-10-25 17:17:27 IST; 6min ago
    Process: 3459495 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 3459495 (code=exited, status=0/SUCCESS)
        CPU: 716us

Oct 25 17:17:27 softsuave-PG037NVQ systemd[1]: Starting Anonymizing overlay network for TCP (multi-instance-master)...
Oct 25 17:17:27 softsuave-PG037NVQ systemd[1]: Finished Anonymizing overlay network for TCP (multi-instance-master).
```
after reloading the service manually also the IP is not changing, you can see `active (exited)` which means its not installed properly. please provide some suggestions

**Comment by Rs6user** [comment]
![Screenshot from 2024-10-29 14-00-35](https://github.com/user-attachments/assets/8107a015-fea0-45ba-96dc-1db4bd0b8b21)

**Comment by Rs6user** [comment]
have the same issue tried everything

**Comment by FDX100** [comment]
> have the same issue tried everything

in section that says
( How many times do you want to change your IP? enter to infinite IP change]) 
if 0 does not work you can leave it blank just press enter  or select it type 1000000

**Comment by FDX100** [comment]
> @FDX100
> 
> ```
> systemctl status tor
> ● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
>      Loaded: loaded (/lib/systemd/system/tor.service; enabled; vendor preset: enabled)
>      Active: active (exited) since Fri 2024-10-25 17:17:27 IST; 6min ago
>     Process: 3459495 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
>    Main PID: 3459495 (code=exited, status=0/SUCCESS)
>         CPU: 716us
> 
> Oct 25 17:17:27 softsuave-PG037NVQ systemd[1]: Starting Anonymizing overlay network for TCP (multi-instance-master)...
> Oct 25 17:17:27 softsuave-PG037NVQ systemd[1]: Finished Anonymizing overlay network for TCP (multi-instance-master).
> ```
> 
> after reloading the service manually also the IP is not changing, you can see `active (exited)` which means its not installed properly. please provide some suggestions

it seems everything works well, and your mistake is happening while putting socks in your browser

**Comment by Gsbsnzmzkjd62** [comment]
_          _______
     /\        | |        |__   __|
    /  \  _   _| |_ ___      | | ___  _ __
   / /\ \| | | | __/ _ \     | |/ _ \| '__|
  / ____ \ |_| | || (_) |    | | (_) | |
 /_/    \_\__,_|\__\___/     |_|\___/|_|
                V 2.1
from mrFD

 http://facebook.com/ninja.hackerz.kurdish/

 change your  SOCKES to 127.0.0.1:9050 

[+] time to change Ip in Sec [type=60] >> 10
[+] How many times do you want to change your IP? enter to infinite IP change] >> 
Starting infinite IP change. Press Ctrl+C to stop.
Traceback (most recent call last):
  File "/usr/share/aut/autoTOR.py", line 72, in <module>
    change()  # Assuming 'change()' is defined elsewhere
    ~~~~~~^^
  File "/usr/share/aut/autoTOR.py", line 39, in change
    print ('[+] Your IP has been Changed to : '+str(ma_ip()))
                                                    ~~~~~^^
  File "/usr/share/aut/autoTOR.py", line 34, in ma_ip
    get_ip= requests.get(url,proxies=dict(http='socks5://127.0.0.1:9050',https='socks5://127.0.0.1:9050'))
            ^^^^^^^^
NameError: name 'requests' is not defined
                                                                                                       
┌──(root㉿MarBurg)-[/home/marburg/Desktop/Auto_Tor_IP_changer]
└─#     


pls help
