### ISSUE TITLE
requests is not defined

### ISSUE THREAD

**Issue by SinanAkkoyun** [FDX100/Auto_Tor_IP_changer#8]
```
 http://facebook.com/ninja.hackerz.kurdish/

[ ok ] Starting tor daemon...done.
 change your  SOCKES to 127.0.0.1:9050

[ ok ] Starting tor daemon...done (already running).
[+] time to change Ip in Sec [type=60] >> 30
[+] how many time do you want to change your ip [type=1000]for infinte ip change type [0] >>0
[ ok ] Reloading tor daemon configuration...done.
Traceback (most recent call last):
  File "/usr/share/aut/autoTOR.py", line 77, in <module>
    change()
  File "/usr/share/aut/autoTOR.py", line 48, in change
    print ('[+] Your IP has been Changed to : '+str(ma_ip()))
  File "/usr/share/aut/autoTOR.py", line 43, in ma_ip
    get_ip= requests.get(url,proxies=dict(http='socks5://127.0.0.1:9050',https='socks5://127.0.0.1:9050'))
NameError: name 'requests' is not defined
```

**Comment by SinanAkkoyun** [comment]
I already did pip install requests and pip3 install requests
